<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr> 
    <td width="1%"><font face="Arial" size="1">&nbsp;</font></td>
    <td width="99%"><font face="Arial" size="1">
	  | <a  class="abc" href="category_view.asp?alph=a">A </a> 
      | <a  class="abc" href="category_view.asp?alph=b">B</a> | <a  class="abc" href="category_view.asp?alph=c">C</a> 
      | <a  class="abc" href="category_view.asp?alph=d">D</a> | <a  class="abc" href="category_view.asp?alph=e">E</a> 
      | <a  class="abc" href="category_view.asp?alph=f">F</a> | <a  class="abc" href="category_view.asp?alph=g">G</a> 
      | <a  class="abc" href="category_view.asp?alph=h">H</a> | <a  class="abc" href="category_view.asp?alph=i">I</a> 
      | <a  class="abc" href="category_view.asp?alph=j">J</a> | <a  class="abc" href="category_view.asp?alph=k">K</a> 
      | <a  class="abc" href="category_view.asp?alph=l">L</a> | <a  class="abc" href="category_view.asp?alph=m">M</a> 
      | <a  class="abc" href="category_view.asp?alph=n">N</a> | <a  class="abc" href="category_view.asp?alph=o">O</a> 
      | <a  class="abc" href="category_view.asp?alph=p">P</a> | <a  class="abc" href="category_view.asp?alph=q">Q</a> 
      | <a  class="abc" href="category_view.asp?alph=r">R</a> | <a  class="abc" href="category_view.asp?alph=s">S</a> 
      | <a  class="abc" href="category_view.asp?alph=t">T</a> | <a  class="abc" href="category_view.asp?alph=u">U</a> 
      | <a  class="abc" href="category_view.asp?alph=v">V</a> | <a  class="abc" href="category_view.asp?alph=w">W</a> 
      | <a  class="abc" href="category_view.asp?alph=x">X</a> | <a  class="abc" href="category_view.asp?alph=y">Y</a> 
      | <a  class="abc" href="category_view.asp?alph=z">Z</a> |</font></td>
  </tr>
  
</table>
